name = "promptimagelab"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "promptimagelab_db"
database_id = "f5ffadf6-b94b-4e35-bac3-2ab92a97f6f5"

[vars]
SITE_URL = "https://promptimagelab.com"
