UPDATE prompts SET
  word_count = 3800,
  reading_time = 16,
  updated_at = datetime('now'),
  content = '<h2>The Science Behind Why Your Instagram DP Decides Your Growth Rate</h2>
<p>Every Instagram interaction begins with a profile picture. When someone encounters your account — in Explore, in a comment section, in search results — their brain processes your DP in approximately 50 milliseconds. That is faster than conscious thought. Before they have read a single word of your bio or seen a single post in your feed, a judgment has already been formed.</p>
<p>Researchers studying social media behavior have documented a consistent pattern: accounts with clear, high-contrast, professionally lit profile pictures receive follow rates two to four times higher than accounts with blurry, poorly lit, or visually cluttered images. This gap holds regardless of content quality. You can have the best content on Instagram and still underperform because your DP is working against you at the crucial first impression moment.</p>
<p>The traditional barrier to a great profile picture has been cost. A session with a portrait photographer runs between 200 and 800 dollars. Studio rental, lighting, post-processing editing — the total investment for a single high-quality headshot can easily exceed a thousand dollars. For individual creators and small businesses, that cost is difficult to justify for something that gets updated every few months anyway.</p>
<p>AI image generation has permanently changed this equation. Midjourney v6, DALL-E 3, and Stable Diffusion XL can now produce portrait images that professional photographers cannot reliably distinguish from actual photography — but only when the prompts are constructed with genuine intentionality. Generic prompts produce generic results. Precisely structured prompts produce images that belong on magazine covers.</p>
<p>This guide gives you 60 precisely structured prompts, a complete framework for understanding why they work, and the technical knowledge to adapt them to your specific situation.</p>

<h2>The Architecture of a High-Performance Instagram DP Prompt</h2>
<p>Understanding prompt structure before you start generating saves enormous time and dramatically improves your results. Every excellent portrait prompt shares a common architecture of five components that work together to give the AI model complete, unambiguous creative direction.</p>
<p><strong>Component One — Subject Anchoring:</strong> Who is in the image and what are their defining visual characteristics? The AI needs to understand the primary subject before it can make good decisions about everything else. Include approximate age range, any distinctive features that matter to you, and the general physical type you want to convey.</p>
<p><strong>Component Two — Photographic Style Reference:</strong> What visual tradition does this image belong to? Fashion editorial photography operates by completely different rules than documentary street photography. Studio portraiture has different conventions than candid lifestyle photography. Naming the style — and ideally naming specific photographers whose work exemplifies it — gives the AI a detailed visual vocabulary to draw from.</p>
<p><strong>Component Three — Light Architecture:</strong> Light is the single variable that separates amateur-looking AI portraits from professional ones. The direction, quality, color temperature, and intensity of light in a portrait determines its entire emotional register. "Good lighting" is not a useful instruction. "Soft north-facing window light with warm fill from below" is a precise, actionable specification.</p>
<p><strong>Component Four — Technical Camera Language:</strong> AI models trained on vast photography datasets respond strongly to camera and lens specifications. Specifying an 85mm f/1.4 lens tells the model exactly how the background should blur, how compressed the facial features should appear, and what the depth of field should look like. This single addition to any prompt significantly improves photorealism.</p>
<p><strong>Component Five — Composition and Cropping:</strong> Instagram displays profile pictures as circles cropped from squares at multiple sizes — 110 pixels in feed contexts, 150 pixels on mobile profiles, and up to 300 pixels on desktop. Your composition instructions must account for this. The subject should be centered, filling at least 60% of the frame, with enough clear margin around the face to survive the circle crop without losing anything important.</p>

<h2>Natural Lifestyle Instagram DP Prompts</h2>
<p>Natural lifestyle portraits work for personal bloggers, wellness creators, travel influencers, and anyone who wants their profile picture to communicate authenticity and warmth. The visual goal is a photograph that looks like it could have been taken by a talented friend rather than in a studio — spontaneous, real, and full of natural light.</p>
<p><strong>Prompt 1 — Golden Hour Classic:</strong> "Outdoor portrait photograph, late afternoon golden hour sunlight from the left side creating warm amber rim light, natural bokeh from shallow depth of field, green vegetation background blurred, genuine relaxed expression with soft smile, slight wind movement in hair, lifestyle photography aesthetic, Canon EOS R5 85mm f/1.4, warm skin tones, photorealistic, 1:1 square crop centered on face"</p>
<p><strong>Prompt 2 — Soft Window Natural:</strong> "Indoor portrait, soft north-facing window light from the left creating gentle graduated shadow, minimal fill from white wall bounce, overcast daylight quality, creamy neutral background, thoughtful genuine expression, fine individual hair strands visible, documentary photography aesthetic, Fujifilm GFX medium format look, neutral warm skin rendering"</p>
<p><strong>Prompt 3 — Dappled Garden:</strong> "Garden portrait, afternoon sunlight filtering through tree leaves creating dappled light patterns on face and background, warm golden spots of light, green bokeh depth, white summer clothing, candid and at ease expression, Fujifilm film simulation aesthetic with fine grain and lifted shadows, rich green saturation, 1:1 circle-crop safe"</p>
<p><strong>Prompt 4 — Beach Sunset:</strong> "Beach portrait, Atlantic coast golden hour, warm burnt orange sky behind, gentle breeze in hair, relaxed authentic smile showing teeth, ocean defocused in background with warm highlights, handheld lifestyle photography feel, slight lens vignette, coastal summer mood, sRGB color space, photorealistic"</p>
<p><strong>Prompt 5 — Morning Coffee:</strong> "Café portrait, early morning warm interior light from large window, steam suggestion in background, casual comfortable styling, genuine absorbed expression looking slightly off-camera, warm amber and terracotta tones, analogue film warmth and slight grain, shallow depth with bokeh of café interior"</p>
<p><strong>Prompt 6 — Urban Street:</strong> "Street portrait, urban environment background with blurred building facades, overcast natural city light, no direct sun creating even soft shadows, smart casual styling, direct confident gaze to camera, street photography aesthetic, 35mm Leica rangefinder camera feel, authentic and unposed"</p>
<p><strong>Prompt 7 — Rooftop City:</strong> "Rooftop portrait, golden hour city skyline background blurred with warm bokeh window lights, slight elevation above city creating dramatic perspective, casual styling with jacket, wind in hair, adventure and ambition in expression, urban lifestyle photography, Canon 85mm lens"</p>

<h2>Professional Instagram DP Prompts for Business and Personal Brand</h2>
<p>Business profiles, coaches, consultants, freelancers, and entrepreneurs need Instagram DPs that communicate authority and approachability simultaneously. The goal is a photograph that makes potential clients feel both confident in your expertise and comfortable reaching out to you.</p>
<p><strong>Prompt 8 — Clean Studio Authority:</strong> "Professional headshot, smooth gradient background from dark charcoal to medium grey, soft studio key light from upper left with subtle fill, Rembrandt triangle of light on shadowed cheek, direct confident eye contact, business casual navy blazer, relaxed composed expression, 85mm portrait lens, sharp focus on eyes, corporate photography quality, photorealistic"</p>
<p><strong>Prompt 9 — Modern Office Natural:</strong> "Business portrait, modern open-plan office background with glass walls and plants at f/2 bokeh, directional natural window light, smart blazer over minimal crew neck, approachable professional expression with slight genuine smile, personal brand photography style, warm and competent mood, photorealistic"</p>
<p><strong>Prompt 10 — Entrepreneur Creative:</strong> "Founder portrait, creative coworking space background with bookshelves and plants blurred, warm ambient light mixed with soft window directional light, business casual in quality fabrics, confident engaged expression, slight forward lean suggesting energy and presence, personal brand photography"</p>
<p><strong>Prompt 11 — Executive Minimalist:</strong> "Executive headshot, pure white seamless background, perfectly even bilateral studio lighting, black premium turtleneck, strong facial structure, composed commanding expression, razor-sharp eye detail, high-key clean aesthetic, Steve Jobs-era minimalism influence, photorealistic corporate photography"</p>
<p><strong>Prompt 12 — Female Leader:</strong> "Female business leader portrait, architectural glass office background blurred, premium blazer in deep emerald, gold statement jewelry, direct powerful gaze, warm but authoritative expression, Sheryl Sandberg executive presence aesthetic, professional lighting, photorealistic, Forbes cover quality"</p>

<h2>Artistic and Editorial Instagram DP Prompts</h2>
<p>For photographers, designers, musicians, writers, and any creative professional who wants their profile picture to be a statement of artistic identity rather than a standard headshot.</p>
<p><strong>Prompt 13 — Film Noir Cinematic:</strong> "Cinematic portrait, 1940s film noir lighting, single hard side light from left casting deep shadow on right side of face, subtle venetian blind shadow pattern across forehead, mysterious expression, black and white treatment with rich silver tones, 35mm film grain, Humphrey Bogart era atmospheric depth"</p>
<p><strong>Prompt 14 — Moody Blue Hour:</strong> "Portrait at civil blue hour, cool twilight ambient light balanced against warm city light bokeh in background, deep blue atmospheric tones on skin with orange counterlight, contemplative introspective expression, anamorphic horizontal lens flare streak, cinematic color grade, Academy ratio crop suggestion"</p>
<p><strong>Prompt 15 — Editorial Fashion:</strong> "High fashion editorial portrait, Vogue Italia aesthetic, asymmetric directional studio strobe creating graphic shadow geometry, avant-garde styling, bold teal and orange color grade, powerful direct stare into lens, magazine spread composition, Steven Meisel influence, ultra-high resolution"</p>
<p><strong>Prompt 16 — Vintage Film:</strong> "Portrait with 1972 Kodachrome film photography aesthetic, warm pushed tones with slight colour shift toward yellow-green in shadows, overexposed highlights with gentle rolloff, natural outdoor setting, authentic vintage styling, Tri-X style grain structure, nostalgic warmth"</p>
<p><strong>Prompt 17 — Renaissance Oil:</strong> "Portrait in the manner of Flemish Renaissance oil painting, single candlelight source from lower left creating chiaroscuro depth, rich jewel-tone clothing with fabric texture detail, museum-quality brushwork visible, Rembrandt self-portrait influence, timeless and majestic, deeply human"</p>

<h2>Complete Platform Guide: Adapting Prompts to Each AI Tool</h2>
<p>Each major AI image tool has distinct strengths and requires slightly different prompt strategies for best results.</p>
<p><strong>Midjourney v6 — Best Overall Realism:</strong> Append <code>--ar 1:1 --style raw --v 6</code> to all portrait prompts. The <code>--style raw</code> flag disables Midjourney''s automatic aesthetic enhancements and produces more neutral, photographic results that are easier to use as actual profile pictures. For facial consistency across multiple images, use <code>--cref [url]</code> with a reference photo. Control how closely facial features are matched using <code>--cw 50</code> (moderate) to <code>--cw 100</code> (strict). For maximum realism, add <code>--stylize 0</code>.</p>
<p><strong>DALL-E 3 via ChatGPT — Best Composition:</strong> DALL-E 3 excels at following complex compositional instructions. Frame prompts conversationally: "A professional portrait photograph of a person in their early 30s, shot with an 85mm lens at f/1.4, soft studio key light from the upper left..." Always add "photorealistic, professional photography, not illustration" to keep outputs photographic rather than painterly. DALL-E 3 handles "centered face, circle-crop safe composition" instructions very reliably.</p>
<p><strong>Stable Diffusion XL — Best Control, Free:</strong> Use Realistic Vision v6 or Juggernaut XL checkpoint. Negative prompt: "cartoon, anime, illustration, low quality, blurry, overexposed, double face, bad anatomy, plastic skin." Sampler: DPM++ 2M Karras. Steps: 30. CFG: 7. Resolution: 1024x1024. For personalized portraits, train a LoRA on 20-30 of your own photos and combine with a portrait checkpoint at 0.7 weight.</p>
<p><strong>Adobe Firefly — Best Commercial Safety:</strong> Use for business and client work where commercial licensing matters. Firefly is trained only on licensed content, making outputs safe for commercial use. Less flexible than Midjourney for specific styles, but more reliable for clean professional headshots.</p>

<h2>Instagram DP Technical Requirements You Cannot Ignore</h2>
<p>Technical mistakes at the generation stage result in profile pictures that look blurry, oddly cropped, or discolored after Instagram processes them. These specifications prevent every common technical problem.</p>
<p>Always generate at 1024x1024 minimum, ideally 2048x2048. Instagram''s upload compression reduces quality significantly, and starting with a higher-resolution source image results in a much crisper final display even after compression.</p>
<p>Instagram stores profile pictures internally at 320x320 pixels. The display sizes are: 110x110 in feed contexts, 150x150 on mobile profiles, and up to 300x300 on desktop. This means fine details — subtle textures, small background elements, intricate hair detail — are essentially invisible at display size. Focus your prompt energy on what reads clearly at 150 pixels: strong face shape, clear lighting contrast, readable expression.</p>
<p>Color space: Always ensure your generated image is in sRGB color space before uploading. Instagram converts everything to sRGB and applies JPEG compression. Images in P3 or ProPhoto color spaces will have colors shift during conversion. Most AI tools generate sRGB by default, but verify if you are post-processing in photo editing software.</p>
<p>The circle crop: Instagram crops your square image to a circle using a center-point crop. Anything in the corners is hidden. Keep your subject''''s face completely within a circle that represents approximately 85% of the image width. Leave at least 7-8% margin on all sides between the face edge and the frame edge.</p>

<h2>20 More Specialized Prompts by Instagram Niche</h2>
<p><strong>Travel Creator:</strong> "Travel portrait, ancient city architecture background blurred, golden afternoon light, authentic smile of genuine discovery, casual adventure clothing, wanderlust energy, lifestyle travel photography, 50mm street photography lens"</p>
<p><strong>Fitness Coach:</strong> "Fitness portrait, outdoor training environment, strong golden morning light, athletic wear in clean neutral tones, powerful but approachable expression, health and vitality visible, sports photography aesthetic, motivational energy"</p>
<p><strong>Beauty Creator:</strong> "Beauty portrait, professional softbox studio lighting creating perfect even skin illumination, flawless editorial makeup, clean cream background, symmetrical composition, beauty campaign photography quality, Glossier-adjacent aesthetic"</p>
<p><strong>Tech Influencer:</strong> "Tech creator portrait, modern minimal workspace background with a single quality device, cool daylight from monitor glow, smart casual styling, intelligent curious expression, clean and precise aesthetic"</p>
<p><strong>Food Blogger:</strong> "Food personality portrait, warm restaurant or kitchen background blurred, tungsten-warm ambient light, genuine warmth and joy in expression, approachable and food-loving energy, culinary lifestyle aesthetic"</p>
<p><strong>Artist/Painter:</strong> "Artist portrait, studio with paintings visible in background, north skylight directional light, paint-stained creative clothing, absorbed authentic expression, raw studio documentary photography feel"</p>
<p><strong>Musician:</strong> "Musician portrait, concert venue or practice room background, dramatic stage-inspired side lighting, instrument hint in composition, passionate authentic expression, rock or acoustic depending on genre, creative identity photography"</p>

<h2>FAQ: Everything Creators Ask About AI Instagram DPs</h2>
<p><strong>How many variations should I generate before choosing?</strong> Generate at minimum 10 to 20 variations before selecting. The first output is almost never the best. Small prompt modifications — changing one lighting term, adjusting one style reference — produce dramatically different results. The best image in a batch of 20 is consistently better than the first output.</p>
<p><strong>Will my followers know it is AI-generated?</strong> At the sizes Instagram displays profile pictures (110px to 300px), even experts cannot reliably identify AI generation. With Midjourney v6 or DALL-E 3, the outputs are genuinely photorealistic at full resolution too. The question of disclosure is an ethical choice — Instagram does not currently require it.</p>
<p><strong>How do I generate something that looks like me specifically?</strong> Midjourney''''s --cref parameter accepts a reference photo URL and attempts to match facial structure and features. Stable Diffusion DreamBooth or LoRA fine-tuning on your own photos produces the most accurate personalized results. DALL-E 3 can incorporate detailed physical descriptions but cannot directly use reference photos.</p>
<p><strong>What file format should I use when uploading?</strong> Upload JPG at maximum quality (quality setting 95+). PNG files are larger but Instagram converts them to JPEG anyway. Avoid uploading heavily compressed JPEGs — Instagram compresses the image again, and double compression produces visible quality loss.</p>
<h2>How to Customise Any Instagram DP Prompt for Your Specific Skin Tone and Features</h2>
<p>Every prompt in this guide is a starting point, not a fixed recipe. The most common mistake people make is copying a prompt exactly and expecting it to match their specific appearance or brand aesthetic. Effective customisation requires understanding which elements to change and which to leave intact.</p>
<p><strong>Adjusting for Skin Tone and Undertone:</strong> AI models respond strongly to specific colour temperature language. For warmer, deeper skin tones, add "warm amber and golden skin tones, rich melanin rendering, beautiful dark skin glow" to your prompt. For lighter skin with cool undertones, try "cool ivory skin tones, blue-pink undertone, porcelain rendering." For medium brown skin with warm undertones, "warm honey and tawny skin tones, golden undertone, sun-kissed rendering" produces excellent results. Avoid generic terms like "realistic skin" — they produce averaged outputs that satisfy no specific aesthetic.</p>
<p><strong>Adjusting for Hair Type and Texture:</strong> Hair is one of the most technically challenging elements in AI portrait generation. Curly and coily hair requires specific vocabulary: "Type 4c natural hair with defined curl pattern and volume" or "tight coils with natural shrinkage and crown volume" both produce much better results than "natural hair." For straight hair, specify the weight and movement: "fine straight hair falling with natural gravity, no added volume." For wavy hair: "2A wave pattern with natural movement and body."</p>
<p><strong>Matching Your Niche Aesthetic:</strong> Your Instagram DP should feel like it belongs on your profile, not like a generic portrait. If your content has a specific colour palette — say, warm terracotta and cream tones with golden accents — include that palette explicitly: "warm terracotta and cream colour palette, amber accent tones, consistent with lifestyle photography aesthetic." This creates visual coherence between your DP and your content that followers notice subconsciously.</p>

<h2>The 10 Most Common Instagram DP Prompt Mistakes (And How to Fix Each One)</h2>
<p>After testing hundreds of prompts and reviewing thousands of AI portrait outputs, the same mistakes appear repeatedly. Each one has a specific fix that produces immediate improvement.</p>
<p><strong>Mistake 1 — Vague lighting descriptions:</strong> "Good lighting" or "studio lighting" gives the AI no useful information. Fix: Specify the lighting pattern by name — "Rembrandt lighting," "loop lighting," "clamshell beauty lighting" — and add the direction: "from the upper left at 45 degrees."</p>
<p><strong>Mistake 2 — Missing lens focal length:</strong> Portraits without lens specifications often look slightly distorted or have unconvincing depth of field. Fix: Always add "85mm f/1.8" or "135mm f/2" to portrait prompts. This single addition improves photorealism dramatically.</p>
<p><strong>Mistake 3 — No circle-crop margin:</strong> Generated at square format and used directly on Instagram, facial features often get cut off at the circle crop. Fix: Add "centered composition with 12% margin on all sides for circle crop" to every Instagram DP prompt.</p>
<p><strong>Mistake 4 — Over-specifying expression:</strong> Describing too many facial expression elements simultaneously — "big smile, bright eyes, raised cheeks, slightly open mouth, genuine happiness" — creates confusion that often produces odd or unnatural expressions. Fix: Specify one clear expression directive: "genuine warm smile" or "composed confident expression."</p>
<p><strong>Mistake 5 — Wrong aspect ratio:</strong> Instagram profile pictures display as circles cropped from squares. Generating at 16:9 or other non-square ratios wastes resolution and produces poor circle crops. Fix: Always generate at 1:1 square, ideally at 1080x1080 or higher.</p>
<p><strong>Mistake 6 — Generic background descriptions:</strong> "Nice background" or "blurred background" produces entirely random results. Fix: Specify the background exactly: "smooth gradient from dark charcoal to medium grey," "outdoor golden hour with blurred green foliage at f/1.4 bokeh," or "white seamless studio background."</p>
<p><strong>Mistake 7 — Competing style references:</strong> Including contradictory style references — "Vogue editorial meets street photography meets Renaissance oil painting" — produces incoherent outputs. Fix: Choose one primary style reference and one secondary at most. Clear hierarchy: "lifestyle photography aesthetic, influenced by Annie Leibovitz editorial work."</p>
<p><strong>Mistake 8 — Not generating enough variations:</strong> Accepting the first output. AI generation involves randomness — the first output is statistically unlikely to be the best. Fix: Generate a minimum of 10 variations before selecting. The best image in a batch of 20 is consistently 30–50% better than the first output by any quality metric.</p>
<p><strong>Mistake 9 — Uploading without upscaling:</strong> Instagram compresses uploaded images significantly. A 512x512 output uploaded directly will look noticeably degraded at display. Fix: Upscale to at least 1080x1080 using Midjourney upscale, an AI upscaler like Topaz Photo AI, or the built-in upscale in your generation tool before uploading.</p>
<p><strong>Mistake 10 — Wrong colour space:</strong> Images in Adobe RGB or P3 colour space undergo colour shifts when Instagram converts them to sRGB for display. Fix: Export in sRGB colour space. Most AI tools generate sRGB by default, but verify if you are post-processing in Photoshop or Lightroom.</p>

<h2>Building a Consistent Instagram Brand Identity Across Multiple Profile Pictures</h2>
<p>If you manage multiple Instagram accounts or update your profile picture frequently, maintaining visual consistency across different generations is a significant challenge. AI models use randomness by default — the same prompt run twice produces different results. Here is a systematic approach to maintaining brand consistency.</p>
<p><strong>The Fixed Template System:</strong> Create a "brand template" prompt that contains all your fixed elements — your colour palette, preferred lighting style, background treatment, and quality descriptors. Only the variable elements (expression, angle, specific framing) change between generations. Every new profile picture starts from the same template, ensuring lighting, colour, and quality are consistent even when other elements change.</p>
<p><strong>Using Seed Values for Reproducibility:</strong> In Midjourney, adding <code>--seed [number]</code> with a specific number allows you to reproduce similar results. Once you find a seed value that produces facial geometry you are happy with, record it and use it for all future variations of that portrait. In Stable Diffusion, setting a specific seed number in the generation parameters produces even more precise reproducibility.</p>
<p><strong>The Reference Photo Approach:</strong> Midjourney''s <code>--cref [url]</code> parameter accepts a URL to a reference image and attempts to match its character likeness. For personal accounts, uploading a real photo of yourself as a reference produces results that maintain facial structure consistency across multiple generations. The <code>--cw</code> parameter controls how strictly the reference is followed: 50 for subtle influence, 100 for close matching.</p>
<p><strong>Batch Processing for Content Calendars:</strong> If you plan to update your profile picture quarterly or seasonally, generate all four seasonal variations in a single session using the same base prompt with only the seasonal light and palette modifications changed. This ensures all four images feel like part of a coherent visual identity rather than four separate, inconsistent portraits.</p>

<h2>Instagram DP Prompts for Specific Creator Niches: 15 More Ready-to-Use Formulas</h2>
<p><strong>Finance and Investment Creator:</strong> "Professional finance creator Instagram DP, confident authoritative expression without corporate stiffness, business casual in quality navy or charcoal, clean neutral office background with subtle financial context, warm studio light, direct camera gaze communicating credibility and trustworthiness, 1:1 circle-crop safe, photorealistic"</p>
<p><strong>Mental Health and Wellness Coach:</strong> "Mental wellness coach Instagram profile portrait, warm and genuinely compassionate expression, soft natural window light from the left, calming sage green or cream tones in background, casual but professional styling, approachable and safe energy, lifestyle photography aesthetic, 85mm lens"</p>
<p><strong>Book and Literature Creator:</strong> "Bookstagrammer creator portrait, warm home library or bookshelf background with spines blurred at f/2, golden late afternoon light, intellectual and curious expression, reading glasses optional, cosy yet thoughtful aesthetic, warm amber tones, documentary lifestyle photography"</p>
<p><strong>Sustainable Living Creator:</strong> "Sustainability creator Instagram DP, outdoor natural setting with organic textures — earth, stone, plants — in blurred background, warm natural light with earthy tones, genuine calm expression connected to nature, minimal makeup and natural styling, earthy muted palette of sage, terracotta, and cream"</p>
<p><strong>Gaming and Esports Creator:</strong> "Gaming creator Instagram profile portrait, gaming setup background with RGB lighting creating colourful atmosphere, energetic confident expression, streetwear or gaming-adjacent styling, vibrant blue-purple-pink colour palette from monitor glow, dynamic and youthful energy, distinctive and high contrast"</p>
<p><strong>Parenting Creator:</strong> "Parenting creator Instagram DP, warm and genuinely joyful expression, natural home environment with soft warm light, approachable authentic styling, real and lived-in rather than perfected aesthetic, connection and warmth visible, lifestyle photography authenticity"</p>
<p><strong>Real Estate Professional:</strong> "Real estate agent Instagram headshot, confident warm approachable smile conveying trustworthiness, business professional styling, modern architectural property background blurred, natural window light, the look of someone who closes deals and genuinely helps people find homes, photorealistic"</p>
<p><strong>Chef and Food Creator:</strong> "Chef and food creator Instagram DP, professional kitchen or restaurant environment background, warm kitchen lighting, genuine passion for food visible in expression, chef whites or culinary apron, high quality food photography aesthetic, warmth and culinary authority balanced"</p>
<p><strong>Podcast Host:</strong> "Podcast host Instagram profile portrait, studio or home recording setup background with microphone and acoustic foam blurred, warm and engaging expression communicating that this person is worth an hour of listening time, natural and genuine personality visible, conversational and intelligent"</p>
<p><strong>Language Learning Creator:</strong> "Language teacher and creator Instagram DP, warm encouraging expression that makes learning feel achievable, clean bright background, culturally inclusive styling, professional but approachable energy, the face of someone who makes complex things clear and enjoyable"</p>'
WHERE slug = 'instagram-dp-ai-prompts';
