"""Add TelemetryLog

Revision ID: 8cdbbd3735e6
Revises: b57138e64a20
Create Date: 2026-08-01 10:49:00.109637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdbbd3735e6'
down_revision: Union[str, Sequence[str], None] = 'b57138e64a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('redacted', sa.Integer(), nullable=False),
    sa.Column('stream', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_logs')
    # ### end Alembic commands ###
